spring.application.name=Proyecto06
server.port=${PORT:8080}

# =======================================================
# CONFIGURACIÓN DE CONEXIÓN A SUPABASE (POSTGRESQL)
# =======================================================
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ffwcytkgoifegzpjpmoa
spring.datasource.password=9PFZXNsKZtomfYNO
spring.datasource.driver-class-name=org.postgresql.Driver

# =======================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# =======================================================
# 'update' creará las tablas automáticamente si no existen en Supabase
<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=none
=======
spring.jpa.hibernate.ddl-auto=update
>>>>>>> 6809b6544fbac8b1de5473cfa62d24051e871b30
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
