spring.application.name=Proyecto06
server.port=${PORT:8081}

spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:20102/railway
spring.datasource.username=root
spring.datasource.password=acBLFbUBsSycyaVgJQwpqGPOTOHodGsM

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

